"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
const today=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};
const hrs=(a,b)=>{if(!a||!b)return 0;let [ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number),x=ah*60+am,y=bh*60+bm;if(y<x)y+=1440;return (y-x)/60};
const money=n=>(Number(n)||0).toFixed(2);
export default function Page(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(()=>{if(typeof window==="undefined")return "";return localStorage.getItem("tips_curier_email")||""}),[pass,setPass]=useState(""),[confirm,setConfirm]=useState(""),[signup,setSignup]=useState(false),[forgot,setForgot]=useState(false),[reset,setReset]=useState(false),[msg,setMsg]=useState("");
 const [tab,setTab]=useState("today"),[date,setDate]=useState(today()),[start,setStart]=useState(""),[end,setEnd]=useState(""),[orders,setOrders]=useState(0),[cash,setCash]=useState(0),[online,setOnline]=useState(0),[days,setDays]=useState([]),[period,setPeriod]=useState("7"),[saving,setSaving]=useState(false),[temsHours,setTemsHours]=useState(0),[temsOrders,setTemsOrders]=useState(0),[temsCash,setTemsCash]=useState(0),[temsOnline,setTemsOnline]=useState(0);
 useEffect(()=>{supabase.auth.getSession().then(x=>{setSession(x.data.session);if(x.data.session) setReset(window.location.hash.includes("type=recovery"))});const {data}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==="PASSWORD_RECOVERY")setReset(true)});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const {data}=await supabase.from("work_days").select("*").eq("user_id",session.user.id).order("work_date",{ascending:false});if(data)setDays(data)}
 useEffect(()=>{if(session)loadDay(date)},[date,session]);
 async function loadDay(d){const {data}=await supabase.from("work_days").select("*").eq("user_id",session.user.id).eq("work_date",d).maybeSingle();if(data){setStart(data.start_time?.slice(0,5)||"");setEnd(data.end_time?.slice(0,5)||"");setOrders(data.orders||0);setCash(Number(data.cash_tips)||0);setOnline(Number(data.online_tips)||0);setTemsHours(Number(data.tems_hours)||0);setTemsOrders(Number(data.tems_orders)||0);setTemsCash(Number(data.tems_cash)||0);setTemsOnline(Number(data.tems_online)||0)}else{setStart("");setEnd("");setOrders(0);setCash(0);setOnline(0);setTemsHours(0);setTemsOrders(0);setTemsCash(0);setTemsOnline(0)}}
 async function save(v){setSaving(true);const {error}=await supabase.from("work_days").upsert({user_id:session.user.id,work_date:date,start_time:v.start||null,end_time:v.end||null,orders:Number(v.orders)||0,cash_tips:Number(v.cash)||0,online_tips:Number(v.online)||0,hours:hrs(v.start,v.end),tems_hours:Number(v.temsHours)||0,tems_orders:Number(v.temsOrders)||0,tems_cash:Number(v.temsCash)||0,tems_online:Number(v.temsOnline)||0,updated_at:new Date().toISOString()},{onConflict:"user_id,work_date"});if(!error)await load();setSaving(false)}
 function change(k,v){const x={start,end,orders,cash,online,[k]:v};({start:setStart,end:setEnd,orders:setOrders,cash:setCash,online:setOnline}[k])(v);clearTimeout(window._t);window._t=setTimeout(()=>save(x),600)}
 function add(k,n){change(k,Number(k==="cash"?cash:online)+n)}
 function changeTems(k,v){const x={start,end,orders,cash,online,temsHours,temsOrders,temsCash,temsOnline,[k]:v};({temsHours:setTemsHours,temsOrders:setTemsOrders,temsCash:setTemsCash,temsOnline:setTemsOnline}[k])(v);clearTimeout(window._tt);window._tt=setTimeout(()=>save(x),600)}
 async function auth(){setMsg("");if(!email||!email.includes("@"))return setMsg("Introdu o adresă de e-mail validă.");if(signup){if(pass.length<6)return setMsg("Parola trebuie să aibă cel puțin 6 caractere.");if(pass!==confirm)return setMsg("Parolele nu coincid.");const r=await supabase.auth.signUp({email,password:pass});if(r.error)setMsg(r.error.message);else{setMsg("Cont creat. Acum te poți autentifica.");setSignup(false);setPass("");setConfirm("")}}else{localStorage.setItem("tips_curier_email",email);const r=await supabase.auth.signInWithPassword({email,password:pass});if(r.error)setMsg(r.error.message)}}
 async function sendReset(){setMsg("");if(!email||!email.includes("@"))return setMsg("Introdu adresa de e-mail a contului.");const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});if(error)setMsg(error.message);else setMsg("Ți-am trimis un link pentru resetarea parolei. Verifică emailul.")}
 async function updatePassword(){setMsg("");if(pass.length<6)return setMsg("Parola trebuie să aibă cel puțin 6 caractere.");if(pass!==confirm)return setMsg("Parolele nu coincid.");const {error}=await supabase.auth.updateUser({password:pass});if(error)return setMsg(error.message);setMsg("Parola a fost schimbată. Te poți autentifica cu noua parolă.");setReset(false);setPass("");setConfirm("");window.history.replaceState({},document.title,window.location.pathname)}
 const rows=useMemo(()=>period==="all"?days:period==="month"?days.filter(x=>String(x.work_date).startsWith(today().slice(0,7))):days.slice(0,7),[days,period]);
 const stats=useMemo(()=>{const h=rows.reduce((a,x)=>a+Number(x.hours||0),0),o=rows.reduce((a,x)=>a+Number(x.orders||0),0),c=rows.reduce((a,x)=>a+Number(x.cash_tips||0),0),n=rows.reduce((a,x)=>a+Number(x.online_tips||0),0);return {d:rows.length,h,o,c,n,co:o?c/o:0,no:o?n/o:0,oh:h?o/h:0}},[rows]);
 async function removeDay(id){if(!confirm("Ștergi această zi?"))return;await supabase.from("work_days").delete().eq("id",id);load();loadDay(date)}
 if(!session&&!reset)return <main className="auth"><div className="card"><h1>🚚 Tips Curier</h1>{forgot?<><h2>🔑 Resetare parolă</h2><p>Introdu emailul contului și îți trimitem un link pentru alegerea unei parole noi.</p><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><button className="primary" onClick={sendReset}>Trimite link de resetare</button><button onClick={()=>{setForgot(false);setMsg("")}}>Înapoi la conectare</button></>:<><p>Contul aplicației este separat de parola e-mailului.</p><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Parolă aplicație" value={pass} onChange={e=>setPass(e.target.value)}/>{signup&&<input type="password" placeholder="Confirmă parola" value={confirm} onChange={e=>setConfirm(e.target.value)}/>}<button className="primary" onClick={auth}>{signup?"Creează cont":"Intră în cont"}</button>{!signup&&<button className="link" onClick={()=>{setForgot(true);setMsg("")}}>Ai uitat parola?</button>}<button onClick={()=>{setSignup(!signup);setMsg("")}}>{signup?"Am deja cont":"Cont nou"}</button>{signup&&<small>Folosește o adresă de e-mail validă și creează o parolă nouă pentru aplicație.</small>}</>}{msg&&<p>{msg}</p>}</div></main>;
 if(reset)return <main className="auth"><div className="card"><h1>🚚 Tips Curier</h1><h2>🔑 Alege o parolă nouă</h2><p>Introdu parola nouă pentru contul tău.</p><input type="password" placeholder="Parolă nouă" value={pass} onChange={e=>setPass(e.target.value)}/><input type="password" placeholder="Confirmă parola nouă" value={confirm} onChange={e=>setConfirm(e.target.value)}/><button className="primary" onClick={updatePassword}>Schimbă parola</button>{msg&&<p>{msg}</p>}</div></main>;
 const hour=hrs(start,end);
 const temsProductivity=temsHours>0?temsOrders/temsHours:0;
 const temsRate=temsProductivity<=2.70?9:temsProductivity<=3.10?10:11;
 const temsOrdersPay=temsOrders*temsRate;

 return <main><header><div><h1>🚚 Tips Curier</h1><small>{session.user.email}</small></div><button onClick={()=>supabase.auth.signOut()}>Ieșire</button></header><nav><button className={tab==="today"?"on":""} onClick={()=>setTab("today")}>Azi</button><button className={tab==="stats"?"on":""} onClick={()=>setTab("stats")}>📊 Statistici</button><button className={tab==="calendar"?"on":""} onClick={()=>setTab("calendar")}>📅 Calendar</button><button className={tab==="profile"?"on":""} onClick={()=>setTab("profile")}>👤 Profil</button><button className={tab==="tems"?"on":""} onClick={()=>setTab("tems")}>TEM’S</button></nav>
 {tab==="today"&&<><section className="card"><div className="row"><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Comenzi<input type="number" min="0" value={orders} onChange={e=>change("orders",e.target.value)}/></label></div><div className="row"><label>Intrare<input type="time" value={start} onChange={e=>change("start",e.target.value)}/></label><label>Ieșire<input type="time" value={end} onChange={e=>change("end",e.target.value)}/></label></div><small>{saving?"Se salvează...":"Salvat automat ✓"}</small></section><div className="grid"><section className="card"><h2>💵 Cash: {money(cash)} lei</h2><button onClick={()=>add("cash",5)}>+5</button><button onClick={()=>add("cash",10)}>+10</button><button onClick={()=>add("cash",15)}>+15</button><button onClick={()=>add("cash",-5)}>-5</button><button onClick={()=>change("cash",prompt("Suma cash totală:",cash)||cash)}>Altă sumă</button></section><section className="card"><h2>💳 Online: {money(online)} lei</h2><button onClick={()=>add("online",5)}>+5</button><button onClick={()=>add("online",10)}>+10</button><button onClick={()=>add("online",15)}>+15</button><button onClick={()=>add("online",-5)}>-5</button><button onClick={()=>change("online",prompt("Suma online totală:",online)||online)}>Altă sumă</button></section></div><section className="stats"><b>ORE<strong>{hour.toFixed(2)}</strong></b><b>COMENZI<strong>{orders}</strong></b><b>CASH<strong>{money(cash)} lei</strong></b><b>ONLINE<strong>{money(online)} lei</strong></b></section></>}
 {tab==="stats"&&<><section className="card"><h2>📊 Statistici</h2><button className={period==="7"?"on":""} onClick={()=>setPeriod("7")}>7 zile</button><button className={period==="month"?"on":""} onClick={()=>setPeriod("month")}>Luna</button><button className={period==="all"?"on":""} onClick={()=>setPeriod("all")}>Tot</button></section><div className="statgrid">{[["ZILE",stats.d],["ORE",stats.h.toFixed(2)],["COMENZI",stats.o],["COMENZI/ORĂ",stats.oh.toFixed(1)],["CASH",money(stats.c)+" lei"],["CASH/COMANDĂ",money(stats.co)+" lei"],["ONLINE",money(stats.n)+" lei"],["ONLINE/COMANDĂ",money(stats.no)+" lei"]].map(x=><div className="stat" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div></>}
 {tab==="calendar"&&<section className="card"><h2>📅 Calendar</h2>{days.length===0?<p>Nu ai zile înregistrate încă.</p>:days.map(d=><div className="history" key={d.id}><span><button onClick={()=>{setDate(d.work_date);setTab("today")}}>{d.work_date}</button><br/><small>{d.orders} comenzi · {Number(d.hours||0).toFixed(2)} ore · cash {money(d.cash_tips)} · online {money(d.online_tips)}</small>{(Number(d.tems_hours||0)>0||Number(d.tems_orders||0)>0||Number(d.tems_cash||0)>0||Number(d.tems_online||0)>0)&&<><br/><small><b>TEM’S:</b> {Number(d.tems_hours||0).toFixed(2)} ore · {Number(d.tems_orders||0)} comenzi · cash {money(d.tems_cash)} · online {money(d.tems_online)}</small></>}</span><span><b>Cash {money(d.cash_tips)} lei</b><br/><b>Online {money(d.online_tips)} lei</b><br/><button onClick={()=>removeDay(d.id)}>Șterge</button></span></div>)}</section>}
 {tab==="tems"&&<><section className="card"><h2>🏢 TEM’S</h2><p>Calculator conform ofertei salariale part-time.</p><div className="row"><label>Ore lucrate<input type="number" min="0" step="0.01" value={temsHours} onChange={e=>changeTems("temsHours",Number(e.target.value)||0)}/></label><label>Comenzi efectuate<input type="number" min="0" step="1" value={temsOrders} onChange={e=>changeTems("temsOrders",Number(e.target.value)||0)}/></label></div><div className="statgrid"><div className="stat"><small>COMENZI/ORĂ</small><strong>{temsProductivity.toFixed(2)}</strong></div><div className="stat"><small>TARIF/COMANDĂ</small><strong>{temsRate} lei</strong></div><div className="stat"><small>VENIT COMENZI</small><strong>{money(temsOrdersPay)} lei</strong></div><div className="stat"><small>BONUS</small><strong>{temsProductivity<=2.70?"0":temsProductivity<=3.10?"1":"2"}</strong></div></div></section><section className="card"><h2>💵 Tips</h2><div className="row"><label>Tips CASH<input type="number" min="0" step="0.01" value={temsCash} onChange={e=>changeTems("temsCash",e.target.value)}/></label><label>Tips ONLINE<input type="number" min="0" step="0.01" value={temsOnline} onChange={e=>changeTems("temsOnline",e.target.value)}/></label></div><div className="stats"><b>CASH<strong>{money(temsCash)} lei</strong></b><b>ONLINE<strong>{money(temsOnline)} lei</strong></b><b>COMENZI<strong>{temsOrders}</strong></b></div></section><section className="card"><h2>📋 Grila TEM’S</h2><p><b>≤ 2,70 comenzi/oră</b> → 9 lei/comandă</p><p><b>2,71 – 3,10</b> → 10 lei/comandă</p><p><b>≥ 3,11</b> → 11 lei/comandă</p><small>Tariful ales se aplică tuturor comenzilor din calcul, în funcție de productivitatea medie.</small><small>Valorile TEM’S se salvează separat pentru fiecare zi. Alege data din „Calendar” pentru a le verifica.</small></section></>}
{tab==="profile"&&<section className="card"><h2>👤 Profil curier</h2><p><b>E-mail</b><br/>{session.user.email}</p><p><b>Zile înregistrate</b><br/>{days.length}</p><hr/><h3>📱 Instalează Tips Curier pe telefon</h3><p><small>Aplicația se deschide direct din browser și o poți pune pe ecranul principal ca o aplicație.</small></p><div className="install-help"><b>🍎 iPhone / iPad (iOS)</b><ol><li>Deschide Tips Curier în <b>Safari</b>.</li><li>Apasă butonul <b>Partajare</b> (pătratul cu săgeata în sus).</li><li>Derulează și alege <b>Adaugă pe ecranul principal</b>.</li><li>Apasă <b>Adaugă</b>. Iconița Tips Curier va apărea pe ecran.</li></ol><b>🤖 Android</b><ol><li>Deschide Tips Curier în <b>Chrome</b>.</li><li>Apasă <b>⋮</b> în colțul din dreapta sus.</li><li>Alege <b>Adaugă la ecranul principal</b> sau <b>Instalează aplicația</b>.</li><li>Confirmă cu <b>Adaugă / Instalează</b>.</li></ol></div></section>}
 </main>
}