"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import "./styles.css";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
const today=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};
const hrs=(a,b)=>{if(!a||!b)return 0;let [ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number),x=ah*60+am,y=bh*60+bm;if(y<x)y+=1440;return (y-x)/60};
const m=n=>(Number(n)||0).toFixed(2);
export default function Page(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(""),[pass,setPass]=useState(""),[signup,setSignup]=useState(false),[msg,setMsg]=useState("");
 const [tab,setTab]=useState("today"),[date,setDate]=useState(today()),[start,setStart]=useState(""),[end,setEnd]=useState(""),[orders,setOrders]=useState(0),[cash,setCash]=useState(0),[online,setOnline]=useState(0),[days,setDays]=useState([]),[period,setPeriod]=useState("7");
 useEffect(()=>{supabase.auth.getSession().then(x=>setSession(x.data.session));const {data}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const {data}=await supabase.from("work_days").select("*").eq("user_id",session.user.id).order("work_date",{ascending:false});if(data)setDays(data)}
 useEffect(()=>{if(session)loadDay(date)},[date,session]);
 async function loadDay(d){const {data}=await supabase.from("work_days").select("*").eq("user_id",session.user.id).eq("work_date",d).maybeSingle();if(data){setStart(data.start_time?.slice(0,5)||"");setEnd(data.end_time?.slice(0,5)||"");setOrders(data.orders||0);setCash(Number(data.cash_tips)||0);setOnline(Number(data.online_tips)||0)}else{setStart("");setEnd("");setOrders(0);setCash(0);setOnline(0)}}
 async function save(v){await supabase.from("work_days").upsert({user_id:session.user.id,work_date:date,start_time:v.start||null,end_time:v.end||null,orders:Number(v.orders)||0,cash_tips:Number(v.cash)||0,online_tips:Number(v.online)||0,hours:hrs(v.start,v.end),updated_at:new Date().toISOString()},{onConflict:"user_id,work_date"});load()}
 function change(k,v){const x={start,end,orders,cash,online,[k]:v};({start:setStart,end:setEnd,orders:setOrders,cash:setCash,online:setOnline}[k])(v);clearTimeout(window._t);window._t=setTimeout(()=>save(x),600)}
 async function auth(){setMsg("");const r=signup?await supabase.auth.signUp({email,password:pass}):await supabase.auth.signInWithPassword({email,password:pass});if(r.error)setMsg(r.error.message);else if(signup)setMsg("Cont creat. Acum te poți autentifica.")}
 const rows=useMemo(()=>period==="all"?days:period==="month"?days.filter(x=>String(x.work_date).startsWith(today().slice(0,7))):days.slice(0,7),[days,period]);
 const stats=useMemo(()=>{const h=rows.reduce((a,x)=>a+Number(x.hours||0),0),o=rows.reduce((a,x)=>a+Number(x.orders||0),0),c=rows.reduce((a,x)=>a+Number(x.cash_tips||0),0),n=rows.reduce((a,x)=>a+Number(x.online_tips||0),0);return {d:rows.length,h,o,c,n,t:c+n,oh:h?o/h:0,to:o?(c+n)/o:0}},[rows]);
 if(!session)return <main className="auth"><div className="card"><h1>🚚 Curier App</h1><p>Introdu e-mailul și parola.</p><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Parolă" value={pass} onChange={e=>setPass(e.target.value)}/><button className="primary" onClick={auth}>{signup?"Creează cont":"Intră în cont"}</button><button onClick={()=>setSignup(!signup)}>{signup?"Am deja cont":"Cont nou"}</button>{msg&&<p>{msg}</p>}</div></main>;
 const total=Number(cash)+Number(online),hour=hrs(start,end);
 return <main><header><div><h1>🚚 Curier App</h1><small>{session.user.email}</small></div><button onClick={()=>supabase.auth.signOut()}>Ieșire</button></header><nav><button className={tab==="today"?"on":""} onClick={()=>setTab("today")}>Azi</button><button className={tab==="stats"?"on":""} onClick={()=>setTab("stats")}>📊 Statistici</button><button className={tab==="calendar"?"on":""} onClick={()=>setTab("calendar")}>📅 Calendar</button><button className={tab==="profile"?"on":""} onClick={()=>setTab("profile")}>👤 Profil</button></nav>
 {tab==="today"&&<><section className="card"><div className="row"><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Comenzi<input type="number" value={orders} onChange={e=>change("orders",e.target.value)}/></label></div><div className="row"><label>Intrare<input type="time" value={start} onChange={e=>change("start",e.target.value)}/></label><label>Ieșire<input type="time" value={end} onChange={e=>change("end",e.target.value)}/></label></div><small>Salvare automată ✓</small></section><div className="grid"><section className="card"><h2>💵 Cash: {m(cash)} lei</h2><button onClick={()=>change("cash",Number(cash)+5)}>+5</button><button onClick={()=>change("cash",Number(cash)+10)}>+10</button><button onClick={()=>change("cash",Number(cash)+15)}>+15</button></section><section className="card"><h2>💳 Online: {m(online)} lei</h2><button onClick={()=>change("online",Number(online)+5)}>+5</button><button onClick={()=>change("online",Number(online)+10)}>+10</button><button onClick={()=>change("online",Number(online)+15)}>+15</button></section></div><section className="stats"><b>ORE<strong>{hour.toFixed(2)}</strong></b><b>COMENZI<strong>{orders}</strong></b><b>TIPS<strong>{m(total)} lei</strong></b><b>LEI/COMANDĂ<strong>{m(orders?total/orders:0)}</strong></b></section></>}
 {tab==="stats"&&<><section className="card"><h2>📊 Statistici</h2><button className={period==="7"?"on":""} onClick={()=>setPeriod("7")}>7 zile</button><button className={period==="month"?"on":""} onClick={()=>setPeriod("month")}>Luna</button><button className={period==="all"?"on":""} onClick={()=>setPeriod("all")}>Tot</button></section><div className="statgrid">{[["ZILE",stats.d],["ORE",stats.h.toFixed(2)],["COMENZI",stats.o],["COMENZI/ORĂ",stats.oh.toFixed(1)],["CASH",m(stats.c)+" lei"],["ONLINE",m(stats.n)+" lei"],["TIPS TOTAL",m(stats.t)+" lei"],["TIPS/COMANDĂ",m(stats.to)+" lei"]].map(x=><div className="stat" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div></>}
 {tab==="calendar"&&<section className="card"><h2>📅 Calendar</h2>{days.map(d=><div className="history" key={d.id}><span>{d.work_date}<br/><small>{d.orders} comenzi · {Number(d.hours||0).toFixed(2)} ore</small></span><b>{m(Number(d.cash_tips)+Number(d.online_tips))} lei</b></div>)}</section>}
 {tab==="profile"&&<section className="card"><h2>👤 Profil curier</h2><p><b>E-mail</b><br/>{session.user.email}</p><p><b>Zile înregistrate</b><br/>{days.length}</p></section>}
 </main>
}